### ISSUE TITLE
httprobe error

### ISSUE THREAD

**Issue by nullblackvoid** [Dheerajmadhukar/karma_v2#1]
Hi,
Httprobe is already added in my system, still getting httprobe error while running.

Error
```
[!] Error: Unable to find httprobe. Make sure it installed OR 
         - GO111MODULE=on go get -v github.com/tomnomnom/httprobe
         - 
         ```

**Comment by Dheerajmadhukar** [comment]
First thing first, This is not related to karma_v2. I did check the same for that. KARMA_v2 is fine.

Still you can check:

a) httprobe binary is available in /bin
b) you must have the latest httprobe 
c) Run the script as root (not sudo)

**Comment by nullblackvoid** [comment]
Hi,
Thank you for your quick response. 
 httprobe is available in go/bin . 
 httprobe is working fine and it's latest version and I did run karma as a root.  still the same error. 
 
 - So I created a new VPS for it, followed every step and still same httprobe error.

**Comment by Dheerajmadhukar** [comment]
Do share the screenshots of following commands

a) # which httprobe
b) # httprobe --help
c) # echo $PATH

**Comment by nullblackvoid** [comment]
Here:
![Screenshot_1284](https://user-images.githubusercontent.com/45512465/132017132-39e2cb87-ecdc-4e9a-a232-e0f288486673.png)

Thanks

**Comment by Dheerajmadhukar** [comment]
You don't have the latest version of httprobe. As i told you , please do check twice :

a) httprobe binary is available in /bin
b) you must have the latest httprobe
c) Run the script as root (not sudo)

**Comment by Dheerajmadhukar** [comment]
Do update now. Its fixed. Thanks :)

**Comment by nullblackvoid** [comment]
Hey yes fixed. 
Working now. 
Thank you for your tool./
