### ISSUE TITLE
Zero findings

### ISSUE THREAD

**Issue by Akriosss47** [Dheerajmadhukar/karma_v2#11]
Please sir dont close my problem,i have latest httprobe and all tools,and i have errors and zero findngs
![Screenshot_2021-10-29_16_06_42](https://user-images.githubusercontent.com/39735447/139495756-ce0bc6bc-185f-442e-9ee6-e25988999efa.png)

**Comment by Dheerajmadhukar** [comment]
I understand the same. But always check every aspect whenever you open an issue. I can see that you have 0 (ZERO) SHODAN query credit left. That is why NO results.

As you say "Don't close the issue" , so you check by your end and kindly close it accordingly :)


### HAPPY TO HELP :)(:

**Comment by Akriosss47** [comment]
> I understand the same. But always check every aspect whenever you open an issue. I can see that you have 0 (ZERO) SHODAN query credit left. That is why NO results.
> 
> As you say "Don't close the issue" , so you check at your end and kindly close it accordingly :)
> 
> ### HAPPY TO HELP :)(:
When i use new generated free key is the same error
Maby its because i use free shodan key,

**Comment by Dheerajmadhukar** [comment]
This is because of you don't have SHODAN credits.
