### ISSUE TITLE
flag provided but not defined - Issue 

### ISSUE THREAD

**Issue by Praveenprajith** [Dheerajmadhukar/karma_v2#12]
![s](https://user-images.githubusercontent.com/24988817/147729104-ee3537ad-46a0-4516-851d-6ea819c36796.jpg)

what does mean?
use command  -> ./karma_v2 -d test.com -l 50 -ip

**Comment by Dheerajmadhukar** [comment]
https://github.com/Dheerajmadhukar/karma_v2/issues/1
