### ISSUE TITLE
 Empty search query Error While running Karma

### ISSUE THREAD

**Issue by lijinta1984** [Dheerajmadhukar/karma_v2#13]
bash karma_v2 -d redacted.com -l -1 -cve
				..,,,,,,,,,.. 					
                     .,;%%%%%%%%%%%%%%%%%%%%;,. 					
                   %%%%%%%%%%%%%%%%%%%%////%%%%%%, .,;%%;,			
            .;%/,%%%%%/////%%%%%%%%%%%%%%////%%%%,%%//%%%, 			
        .,;%%%%/,%%%///%%%%%%%%%%%%%%%%%%%%%%%%%%%%,////%%%%;, 			
     .,%%%%%%//,%%%%%%%%%%%%%%%%@@%a%%%%%%%%%%%%%%%%,%%/%%%%%%%;, 		
   .,%//%%%%//,%%%%///////%%%%%%%@@@%%%%%%///////%%%%,%%//%%%%%%%%, 		
 ,%%%%%///%%//,%%//%%%%%///%%%%%@@@%%%%%////%%%%%%%%%,/%%%%%%%%%%%%% 		
.%%%%%%%%%////,%%%%%%%//%///%%%%@@@@%%%////%%/////%%%,/;%%%%%%%%/%%% 		
%/%%%%%%%/////,%%%%///%%////%%%@@@@@%%%///%%/%%%%%//%,////%%%%//%%% 		
%//%%%%%//////,%/%a\`   a%///%%%@@@@@@%%////a    a%%%%,//%///%/%%%%% 		
%///%%%%%%///,%%%%@@aa@@%//%%%@@@@S@@@%%///@@aa@@%%%%%,/%////%%%%% 		
%%//%%%%%%%//,%%%%%///////%%%@S@@@@SS@@@%%/////%%%%%%%,%////%%%%%		
%%//%%%%%%%//,%%%%/////%%@%@SS@@@@@@@S@@@@%%%%/////%%%,////%%%%%		
  `%%%//%%%%/,%%%%@%@@@@@@@@@@@@@@@@@@@@@@@@@S@@%%%%%,/////%%			
   `%%%//%%%/,%%%@@@SS@@SSs@@@@@@@@@@@@@sSS@@@@@@%%%,//%%//%			
    `%%%%%%/  %%S@@SS@@@@@Ss` .,,.    .sS@@@S@@@@%.  ///%/%			
      `%%%/    %SS@@@@SSS@@S.         .S@@SSS@@@@.    //%%			
               /`S@@@@@@SSSSSs,     ,sSSSSS@@@@@. 				
                 \@@@@@@@@@@@@@Ss,sS@@@@@@@@@@@./ 				
                  \@@@@@@@@@@@@@.@@@@@@@@@@@.// 				
                   \00aaaaaaaaa00a00aaaaaaa00/ 					
                    \@@000000000000000000@@@/					
                     00000000000000@@@@@@@@@ 					
╭───────────────────────────────────────────────────────────────────────────────╮
   ⡷⠂𝚔𝚊𝚛𝚖𝚊 𝚟𝟸⠐⢾ 					KARMA IS MY BITCH.....🧠

		 - https://github.com/Dheerajmadhukar
		 - https://twitter.com/Dheerajmadhukar
╰───────────────────────────────────────────────────────────────────────────────╯

╔════════════════════════════════════════════════════════════════════════════════╗
  Shodan Result Count  [ No API Credits Use ] 
╚════════════════════════════════════════════════════════════════════════════════╝

Query credits available: 99
Scan credits available: 100
    
Error: Empty search query

**Comment by Dheerajmadhukar** [comment]
provide screenshot or GIF

**Comment by lijinta1984** [comment]
![error](https://user-images.githubusercontent.com/75410857/147929478-5cc5db87-5549-47ef-8c6f-af060918b2fa.jpg)

**Comment by lijinta1984** [comment]
Please find above

**Comment by Linuxinet** [comment]
Yes , Same issue For me from Last Night
![Screenshot_20220104-084352_Termux](https://user-images.githubusercontent.com/55936553/148004856-cbc41489-d017-437a-90d9-aa53bf9d8f36.png)

**Comment by Praveenprajith** [comment]
I also same issue -> ./karma_v2 -d attackers.com -l 200 -ip
![image](https://user-images.githubusercontent.com/24988817/149733042-8e67ba66-796e-43ce-9680-f188ecfad419.png)

**Comment by Dheerajmadhukar** [comment]
Resolved in newer version, will upgrade soon.

**Comment by d4op** [comment]
updated ?

**Comment by Dheerajmadhukar** [comment]
Updated locally,  I will push the newer version soon on github :)


Keep In touch :)
