### ISSUE TITLE
Unable to find httprobe.  Make sure it installed OR

### ISSUE THREAD

**Issue by bigverm23** [Dheerajmadhukar/karma_v2#15]
Ubuntu Server 
installed using the following steps:
[](https://github.com/Dheerajmadhukar/karma_v2#2-install-shodan--mmh3-python-module)[](https://github.com/Dheerajmadhukar/karma_v2#3-install-json-parser-jq)[](https://github.com/Dheerajmadhukar/karma_v2#4-install-httprobe-tomnomnom-to-probe-the-requests)1. Clone the repo
# git clone https://github.com/Dheerajmadhukar/karma_v2.git
2. Install shodan & mmh3 python module
# python3 -m pip install shodan mmh3
3. Install JSON Parser [JQ]
# apt install jq -y
4. Install httprobe [@tomnomnom](https://github.com/tomnomnom/httprobe)[](https://github.com/Dheerajmadhukar/karma_v2#5-install-interlace-codingo-to-multithread-follow-the-codingo-interlace-repo-instructions) to probe the requests
# GO111MODULE=on go get -v github.com/tomnomnom/httprobe
5. Install Interlace [@codingo](https://github.com/codingo/Interlace.git)[](https://github.com/Dheerajmadhukar/karma_v2#6-install-nuclei-projectdiscovery) to multithread [Follow the codingo interlace repo instructions]
# git clone https://github.com/codingo/Interlace.git & install accordingly. 
6. Install nuclei [@projectdiscovery](https://github.com/Dheerajmadhukar/karma_v2/blob/main/github.com/projectdiscovery/nuclei)[](https://github.com/Dheerajmadhukar/karma_v2#7-install-lolcat)[](https://github.com/Dheerajmadhukar/karma_v2#8-install-anew)
# GO111MODULE=on go get -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei
7. Install lolcat
# apt install lolcat -y
8. Install anew
# GO111MODULE=on go get -u github.com/tomnomnom/anew

bash karma_v2 -h results in the error message: [!] Error: Unable to find httprobe. Make sure it installed OR 
	 - GO111MODULE=on go get -v github.com/tomnomnom/httprobe

**Comment by Dheerajmadhukar** [comment]
Install using this command:
# go install -v github.com/tomnomnom/httprobe@latest
