### ISSUE TITLE
I'm unable to print the output from karma_v2

### ISSUE THREAD

**Issue by s3ctat0r** [Dheerajmadhukar/karma_v2#17]
I believe karma_v2 is a great tool for bug bounty hunters & red teamers.
After completing scan, I'm getting a output folder in which all the results are .json.gz format after gunzip-ing the files they are in json format which makes unable to read.
I think there might be some way to get the scanning results displayed in the Banner of the scan itself?

**Comment by ndeepak** [comment]
I think, just _-l -1_ will do the work. Avoid using -s
