### ISSUE TITLE
ALL reqiment install  but error 

### ISSUE THREAD

**Issue by Jmehta10** [Dheerajmadhukar/karma_v2#19]
(tutorial-env) root@debian-s-1vcpu-2gb-blr1-01:~/karma_v2# apt install lolcat -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
lolcat is already the newest version (100.0.1-3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
(tutorial-env) root@debian-s-1vcpu-2gb-blr1-01:~/karma_v2# 

ALL INSTALL 
BUT THIS error 
(tutorial-env) root@debian-s-1vcpu-2gb-blr1-01:~/karma_v2# bash karma_v2 

[!] Error: Unable to find lolcat. Make sure it installed OR 
         - apt install lolcat -y
         how to fix

**Comment by ndeepak** [comment]
Check if, lolcat is installed or not
By, _lolcat --version_   and _which lolcat_
Reinstall lolcat
_sudo apt-get remove lolcat_
_sudo apt-get install lolcat -y_
Check Environment variables. _export PATH=$PATH:/usr/..._

**Comment by Dheerajmadhukar** [comment]
[Check_installed_tools](https://github.com/Dheerajmadhukar/karma_v2/blob/main/install.sh)
