### ISSUE TITLE
please anyone can help ? 

### ISSUE THREAD

**Issue by 0xMunafik** [Dheerajmadhukar/karma_v2#21]
i already installed anew and this error keep appers to me every time i run karma 
Error: Unable to find anew. Make sure it installed OR
         - GO111MODULE=on go get -u github.com/tomnomnom/anew

        solved 👍 
export PATH="$PATH:$(go env GOBIN):$(go env GOPATH)/bin"

**Comment by Dheerajmadhukar** [comment]
Do check GOPATH env.
