### ISSUE TITLE
jq: parse error: Invalid numeric literal

### ISSUE THREAD

**Issue by rongabay1** [Dheerajmadhukar/karma_v2#23]
![dddccc](https://github.com/Dheerajmadhukar/karma_v2/assets/116272706/2b270c39-89bb-44e0-ae2d-7ff09f8f84f7)

I get error in ASN section when i run this command "bash karma_v2 -d 'sub.domain.com' -l -1 -deep"

**Comment by Dheerajmadhukar** [comment]
I am working on new updates in Karma_v2. Will update with fix very soon. Keep in touch
