### ISSUE TITLE
Getting blank results and an error "Usage: grep [OPTION]... PATTERNS [FILE]..."

### ISSUE THREAD

**Issue by plavanabond** [Dheerajmadhukar/karma_v2#25]
Getting blank results and an error "Usage: grep [OPTION]... PATTERNS [FILE]..." . No inscope and out of scope IP's and tool showing error:
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
![error](https://github.com/Dheerajmadhukar/karma_v2/assets/115732259/88092c92-9dcb-4776-a515-f6fcd8171a63)

**Comment by Dheerajmadhukar** [comment]
Yes ! It resolved in newer version. I will publish the same very soon. Keep in touch

**Comment by plavanabond** [comment]
Thanks. When will the new version be released?
