### ISSUE TITLE
Any new validation mode ?

### ISSUE THREAD

**Issue by OFJAAAH** [Dheerajmadhukar/karma_v2#3]
Congratulations for the tool.. 
But I already have httprobe would there be any other validation method?

![image](https://user-images.githubusercontent.com/70953773/132024211-5272423c-0c08-4864-a56a-f52730dccf0b.png)

**Comment by Dheerajmadhukar** [comment]
Please check:

httprobe binary is available in /bin

**Comment by Dheerajmadhukar** [comment]
![lol](https://user-images.githubusercontent.com/9442273/132029921-fbb485eb-4220-4e6c-b7c6-fec0db19a5a4.png)


Its working for me. But still you face the same issue, just let me know

**Comment by OFJAAAH** [comment]
![image](https://user-images.githubusercontent.com/70953773/132030173-e05fe4f1-e3c1-47c3-8a9b-7e4bdfe3a776.png)

same problem my friend

**Comment by OFJAAAH** [comment]
![image](https://user-images.githubusercontent.com/70953773/132030287-a706e9ae-ccd3-4917-b746-c477464fca20.png)

**Comment by Dheerajmadhukar** [comment]
I changed the requirement validation. Do run `bash karma -u` OR `git pull` & let me know :)

**Comment by OFJAAAH** [comment]
![image](https://user-images.githubusercontent.com/70953773/132032215-d661d272-7276-4232-a4e4-bf6a71e6ede1.png)


Perfect bro!

**Comment by Dheerajmadhukar** [comment]
Happy to help 👍
