### ISSUE TITLE
No Api Found

### ISSUE THREAD

**Issue by awais922609** [Dheerajmadhukar/karma_v2#4]
Hi, I hope you are good. I am pass through this issue since v1 that when i run this it says me no api found but when i go to karma folder and type gedit .token, i found that token is placed there and everything is ok but when i try to run same problem comes again. Please Help. One more thing that we have to place that  shodan token for which you have given the command cat > .token in shodan folder or somewhere else ?

**Comment by Dheerajmadhukar** [comment]
You need to put the API key on the same directory 
$ cat > .token
SHODAN_KEY

Then script will auto init.

Its better to share the screenshot with complete process of error.

**Comment by Dheerajmadhukar** [comment]
I am going to close this issue. Feel free to reopen if you face any issue :)
