### ISSUE TITLE
flag provided but not defined: -prefer-https

### ISSUE THREAD

**Issue by lijinta1984** [Dheerajmadhukar/karma_v2#8]
Hi Dheeraj,
When i tried to run the tool on a target with IP mode,the following error got output:

**In-Scope-IPs [ Validated by CN=redacted.com ] 
╚════════════════════════════════════════════════════════════════════════════════╝
**flag provided but not defined: -prefer-https
Usage of httprobe:
  -c int
    	set the concurrency level (default 20)
  -p value
    	add additional probe (proto:port)
  -s	skip the default probes (http:80 and https:443)
  -t int
    	timeout (milliseconds) (default 10000)
  -v	output errors to stderr
Traceback (most recent call last):
  File "/usr/local/bin/interlace", line 33, in <module>
    sys.exit(load_entry_point('Interlace==1.9.5', 'console_scripts', 'interlace')())
  File "/usr/local/lib/python3.9/dist-packages/Interlace-1.9.5-py3.9.egg/Interlace/interlace.py", line 36, in main
  File "/usr/local/lib/python3.9/dist-packages/Interlace-1.9.5-py3.9.egg/Interlace/lib/threader.py", line 101, in __init__
  File "/usr/local/lib/python3.9/dist-packages/Interlace-1.9.5-py3.9.egg/Interlace/interlace.py", line 11, in task_queue_generator_func
  File "/usr/local/lib/python3.9/dist-packages/Interlace-1.9.5-py3.9.egg/Interlace/lib/core/input.py", line 264, in process_data_for_tasks_iterator
Exception: No target provided, or empty target list
╔════════════════════════════════════════════════════════════════════════════════╗
  Out-Of-Scope-IPs [ Verified by SSL/TLS certificate subject CN ] 
╚════════════════════════════════════════════════════════════════════════════════╝
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.****

Please support to understand this message and how to rectify the error.

**Comment by lijinta1984** [comment]
Hi Dheeraj,

I have updated the Httprobe tool from Tomnomnom.But the error message shown above still remain.

**Comment by Dheerajmadhukar** [comment]
As i can see in your error...

_Usage of httprobe:
-c int
set the concurrency level (default 20)
-p value
add additional probe (proto:port)
-s skip the default probes (http:80 and https:443)
-t int
timeout (milliseconds) (default 10000)
-v output errors to stderr_

You dont have an option named as '-prefer-https'.

If you upgraded the same, output must be this
# httprobe -h
_Usage of httprobe:
  -c int
        set the concurrency level (split equally between HTTPS and HTTP requests) (default 20)
  -method string
        HTTP method to use (default "GET")
  -p value
        add additional probe (proto:port)
  **-prefer-https
        only try plain HTTP if HTTPS fails**
  -s    skip the default probes (http:80 and https:443)
  -t int
        timeout (milliseconds) (default 10000)_

**Comment by gpxlnx** [comment]
To solve this error you need to install httprobe from branch master

go install github.com/tomnomnom/httprobe@master
